### PR TITLE
Add initial categories query to ProductResolver

### PR DESCRIPTION
**Pull request by jtaaa**
## What's changed

We have a shared `ProductCategory` enum. We also have `getStringEnumKeys` and `getStringEnumValues` util functions.

I've updated the type of the category field on the `ProductModel` to be a `ProductCategory`.

## Notes

In the future we may want to do more with categories like storing them in the DB and allowing admins to dynamically update them. For now having them static is fine.

### CODE REVIEW

**Comment by jtaaa** [comment]
Task linked: [CU-b8n1y3 Add Product Form](https://app.clickup.com/t/b8n1y3)

**Review by chriskrogh — COMMENTED** [review]
Why do we need this? If this is just a static array, then can we just keep this in shared / client depending on where it's needed? How come we have to fetch it?

**Comment by jtaaa** [comment]
You're right! It really doesn't need to be fetched at all if it's static. I'll remove this query and move the categories to `shared`

In the future we may move it back to a query and add the categories to a DB table to make them dynamic.

**Review by chriskrogh — APPROVED** [review]
Is there a reason why we'd want to store these in the db in the future?

**Comment by jtaaa** [comment]
Not definitely but we may want to allow admins to update/add categories dynamically instead of releasing a new build. Maybe we'll find that this isn't necessary at all.

**Pull request merged**
