### PR TITLE
Replace shippingLabelUrl with sysShippingInfo

### PR DESCRIPTION
**Pull request by jtaaa**
## What's changed

Instead of the `shippingLabelUrl` field on the `OrderModel` we now have the `sysShippingDetails` field which stores select information from the UPSL API.

## Notes

We only store the data that would be useful to show to customers in the DB but we will also log the request and response of every request to the UPSL API (coming soon!).

### CODE REVIEW

**Comment by jtaaa** [comment]
Task linked: [CU-c0guu7 Add sysDeliveryFee query](https://app.clickup.com/t/c0guu7)

**Review by chriskrogh — COMMENTED** [review]
This looks very similar to https://github.com/SYSTT/sys-monorepo/pull/73
Maybe the base of this PR is not the right branch?

**Comment by jtaaa** [comment]
It looks like GitHub _finally_ supports automatically changing the base branch when the base branch is merged. But maybe because we squash our commits the changes from the last PR are showing up here even though they are already in master

**Comment by jtaaa** [comment]
Merging `master` into this branch did it so that only the current changes are shown

**Review by chriskrogh — APPROVED** [review]

**Pull request merged**
