### PR TITLE
[CU-behug8] Redirect if authenticated

### PR DESCRIPTION
**Pull request by jtaaa**
### What's Changed

Added optional `guardAuthentication` flag to the `GuardedRoute` component. When enabled the `GuardedRoute` will guard routes against authentication (redirect to `Path.Onboarding` if authenticated). This also disables the default of guarding against unauthenticated.

### CODE REVIEW

**Comment by jtaaa** [comment]
Task linked: [CU-behug8 Redirect from SignIn and SignUp page if authenticated](https://app.clickup.com/t/behug8)

**Comment by jtaaa** [comment]
Task linked: [CU-bmhppu Add Onboarding Page](https://app.clickup.com/t/bmhppu)

**Comment by jtaaa** [comment]
Btw I just started using the GitHub PR and Issues extension in VSCode and it's nice!

```
Name: GitHub Pull Requests and Issues
Id: github.vscode-pull-request-github
Description: Pull Request and Issue Provider for GitHub
Version: 0.19.0
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
```

**Comment by jtaaa** [comment]
Added this comment from within VSCode :rocket:

**Comment by chriskrogh** [comment]
> Btw I just started using the GitHub PR and Issues extension in VSCode and it's nice!
> 
> > Name: GitHub Pull Requests and Issues
> > Id: github.vscode-pull-request-github
> > Description: Pull Request and Issue Provider for GitHub
> > Version: 0.19.0
> > Publisher: GitHub
> > VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

Whaaa
I might give it a go. What do you mostly use it for?

**Comment by jtaaa** [comment]
> > Btw I just started using the GitHub PR and Issues extension in VSCode and it's nice!
> 
> > Name: GitHub Pull Requests and Issues
> > Id: github.vscode-pull-request-github
> > Description: Pull Request and Issue Provider for GitHub
> > Version: 0.19.0
> > Publisher: GitHub
> > VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

Whaaa
I might give it a go. What do you mostly use it for? 

I've been using it to go through these reviews. I'm commenting from vscode!

**Pull request merged**
